# Generated by Django 4.0.5 on 2022-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_desc',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
