# Generated by Django 4.0.5 on 2022-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_post_grouppostcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppostcomment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='grouppostcomment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
