# Generated by Django 4.0.5 on 2022-07-25 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_remove_grouppostcomment_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, default=None, upload_to='publicevents_banner')),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupEvent',
            },
        ),
    ]
