# Generated by Django 4.0.5 on 2022-07-25 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_groupevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupEventComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupevent')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupEvent_Comment',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.groupevent')),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('rsvp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupEventRSVP',
                'unique_together': {('group_id', 'rsvp_id', 'event_id')},
            },
        ),
    ]
