# Generated by Django 4.0.5 on 2022-07-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_groupeventcomment_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeventcomment',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
