# Generated by Django 4.0.5 on 2022-07-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_groupeventcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppostcomment',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
